TRANSLATIONS = {
    "en": {
        "app_title": "PySec Auditor",
        "description": "Advanced auditing with AI, threat-intel, CVE matching, and continuous scans.",
        "arg_url": "Target URL to scan (example.com)",
        "arg_key": "Premium key to unlock features",
        "arg_deep": "Run deep premium vulnerability scan (premium only)",
        "arg_intel": "Run threat intelligence lookups (premium only)",
        "arg_report": "Generate report: summary or full (full includes HTML/PDF if available)",
        "arg_continuous": "Run continuous scans every N seconds (premium only)",
        "arg_api": "API mode: JSON request file (read url and key)",
        "arg_update": "Auto-update from given URL (premium recommended)",
        "arg_output": "Output prefix for reports",
        "error_no_url": "Error: No target URL provided. Use -u or --url. See -h for help.",
        "continuous_requires_premium": "Continuous mode requires premium key. Aborting.",
        "running_premium": "Running premium scan...",
        "running_free": "Running limited free scan...",
        "report_generated": "Reports generated:",
        "ai_summary_title": "AI Risk Summary",
        "threat_intel_title": "Threat Intel",
    },
    "id": {
        "app_title": "PySec Auditor",
        "description": "Audit tingkat lanjut dengan AI, intelijen ancaman, pencocokan CVE, dan pemindaian berkelanjutan.",
        "arg_url": "Target URL untuk dipindai (contoh.com)",
        "arg_key": "Kunci premium untuk membuka fitur",
        "arg_deep": "Jalankan scan kerentanan mendalam (hanya premium)",
        "arg_intel": "Lakukan lookup intelijen ancaman (hanya premium)",
        "arg_report": "Buat laporan: summary atau full (full termasuk HTML/PDF jika tersedia)",
        "arg_continuous": "Jalankan pemindaian kontinu setiap N detik (hanya premium)",
        "arg_api": "Mode API: file request JSON (baca url dan key)",
        "arg_update": "Auto-update dari URL yang diberikan (direkomendasikan premium)",
        "arg_output": "Prefix output untuk laporan",
        "error_no_url": "Kesalahan: Tidak ada target URL. Gunakan -u atau --url. Lihat -h untuk bantuan.",
        "continuous_requires_premium": "Mode kontinu memerlukan kunci premium. Batal.",
        "running_premium": "Menjalankan pemindaian premium...",
        "running_free": "Menjalankan pemindaian gratis terbatas...",
        "report_generated": "Laporan dibuat:",
        "ai_summary_title": "Ringkasan Risiko AI",
        "threat_intel_title": "Intelijen Ancaman",
    },
    "es": {
        "app_title": "PySec Auditor",
        "description": "Auditoría avanzada con IA, inteligencia de amenazas, coincidencia CVE y escaneos continuos.",
        "arg_url": "URL objetivo a escanear (example.com)",
        "arg_key": "Clave premium para desbloquear funciones",
        "arg_deep": "Ejecutar escaneo de vulnerabilidades profundo (solo premium)",
        "arg_intel": "Realizar búsquedas de inteligencia de amenazas (solo premium)",
        "arg_report": "Generar informe: resumen o completo (completo incluye HTML/PDF si está disponible)",
        "arg_continuous": "Ejecutar escaneos continuos cada N segundos (solo premium)",
        "arg_api": "Modo API: archivo JSON de solicitud (leer url y key)",
        "arg_update": "Auto-actualizar desde URL dada (recomendado premium)",
        "arg_output": "Prefijo de salida para informes",
        "error_no_url": "Error: No se proporcionó URL objetivo. Use -u o --url. Vea -h para ayuda.",
        "continuous_requires_premium": "El modo continuo requiere clave premium. Abortando.",
        "running_premium": "Ejecutando escaneo premium...",
        "running_free": "Ejecutando escaneo gratuito limitado...",
        "report_generated": "Informes generados:",
        "ai_summary_title": "Resumen de Riesgo AI",
        "threat_intel_title": "Intel de Amenazas",
    },
    "ar": {
        "app_title": "مدقق PySec",
        "description": "تدقيق متقدم مع الذكاء الاصطناعي، استخبارات التهديدات، مطابقة CVE، والمسح المستمر.",
        "arg_url": "عنوان URL الهدف للفحص (مثال.com)",
        "arg_key": "مفتاح بريميوم لفتح الميزات",
        "arg_deep": "تشغيل فحص ثغرات عميق (بريميوم فقط)",
        "arg_intel": "تشغيل فحوصات استخبارات التهديدات (بريميوم فقط)",
        "arg_report": "إنشاء تقرير: ملخص أو كامل (الكامل يتضمن HTML/PDF إذا كان متاحاً)",
        "arg_continuous": "تشغيل المسح المستمر كل N ثانية (بريميوم فقط)",
        "arg_api": "وضع API: ملف JSON للطلب (اقرأ url و key)",
        "arg_update": "التحديث التلقائي من عنوان URL المعطى (مستحسن للبريميوم)",
        "arg_output": "بادئة الإخراج للتقارير",
        "error_no_url": "خطأ: لم يتم توفير عنوان URL الهدف. استخدم -u أو --url. راجع -h للمساعدة.",
        "continuous_requires_premium": "وضع الاستمرار يتطلب مفتاح بريميوم. إنهاء.",
        "running_premium": "تشغيل فحص بريميوم...",
        "running_free": "تشغيل فحص مجاني محدود...",
        "report_generated": "تم إنشاء التقارير:",
        "ai_summary_title": "ملخص خطر الذكاء الاصطناعي",
        "threat_intel_title": "استخبارات التهديد",
    }
}
def t(key: str, lang: str = "en") -> str:
    if not key: return ""
    if not lang: lang = "en"
    lang = lang.lower()
    if '-' in lang: lang = lang.split('-')[0]
    if lang in TRANSLATIONS and key in TRANSLATIONS[lang]: return TRANSLATIONS[lang][key]
    return TRANSLATIONS.get('en', {}).get(key, key)
